"""Implementation baseline models."""

from pydantic import BaseModel, Field


class ExpectedFile(BaseModel):
    """File expected to be added, modified, or removed during implementation."""

    path: str = Field(description="Repository-relative file path")
    action: str = Field(
        default="modify", description="Expected file action: add, modify, or delete"
    )


class ImplementationBaseline(BaseModel):
    """The central implementation contract generated by CodeAlign.

    Captures expected files, symbols, architectural constraints, and impact
    before implementation begins. Acts as the handoff contract to coding agents.
    """

    version: str = Field(default="0.1.0", description="Baseline schema version")
    plan_title: str = Field(default="", description="Title of the associated implementation plan")
    expected_files: list[ExpectedFile] = Field(
        default_factory=list,
        description="Files expected to be touched by the implementation",
    )
    expected_symbols: list[str] = Field(
        default_factory=list,
        description="Key symbols (classes, functions, methods) expected to be added or modified",
    )
    constraints: list[str] = Field(
        default_factory=list,
        description="Architectural or structural constraints that must not be violated",
    )
